
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prescription_price_development

test:
  <<: *default
  database: prescription_price_test

production:
  <<: *default
  database: prescription_price_production
  username: prescription_price
  password: <%= ENV['PRESCRIPTION_PRICE_DATABASE_PASSWORD'] %>
